### ISSUE TITLE
Project Management: Git Issues use in project 

### ISSUE THREAD

**Issue by russellwjoel** [aanchan/synap-epics#17]
As an aside: I am not sure where these project management idea should live?  Epics repo keeps them clear of code Issues 

When the project management tools are in their early phase we should create some time to refine our tools are processes. We could try them out in sprints and then comment on them during retrospectives. 

Some of the topics: 

- Templates for each issue type (e.g. bug, feature, epic, ... etc.)
- Issue title conventions . (define a standard practice and document it) 
- Label conventions (define standard practice for labels and create visuals for each issue category and their labels)
     
    e.g.    bugfix
                             labels:  Major,  Minor,  Cosmetic

    e.g.  Enhancement 
                           labels: Nice have, Must have, Could have. 

All the while keeping things light weight and most importantly consistent!

**Comment by aanchan** [comment]
Hey @russellwjoel while creating a release, I'm used to good project managers creating release notes. Its a pain to create them manually though. I'd almost use something like this https://github.com/github-tools/github-release-notes. The use of `gren` talks about the wise use of Github issues. Take a look.
