### ISSUE TITLE
Project Management: Integrate Zenhub with Slack

### ISSUE THREAD

**Issue by russellwjoel** [aanchan/synap-epics#18]
A possible team tool:

https://www.zenhub.com/blog/zenhub-slack/

**Comment by aanchan** [comment]
Yeah, I have github and slack integrated on my personal channel. I was afraid it might get too noisy on Slack for everybody. The jury is still out. Perhaps integrate it in your own personal channel? 
![selection_249](https://user-images.githubusercontent.com/3464128/52673526-e7009e80-2ed5-11e9-9fbe-ad425ec05f52.png). @ikemesit is OK keeping it on email. Also can have these issues in synap-epics to keep these issues clean @russellwjoel ?

**Comment by russellwjoel** [comment]
Nice! - I'll check it out
