### ISSUE TITLE
Project Management: Git Issues - Labels 

### ISSUE THREAD

**Issue by russellwjoel** [aanchan/synap-epics#21]

**Comment by russellwjoel** [comment]
Ideas for labels. 
______
### Labels 
___
###   Category Labels 
used across all stages
_(to match some of git flow conventions)_
- feature 
- bugFix
- devOps
___
### Action Labels
_varying for each stage of Kanban_
**before sprint labels**
- estimate.  (required time estimate for ticket) - backlog and icebox
- break down. (too large an issue that requires breaking down into smaller chunks - backlog and icebox

**during sprint labels**
used within sprint
- ready for review - QA/Reivew
- rework -
- need help
___
### Priority Labels
Used across all stages - to indicate priority. 
- Very High
- High
- Medium
- Low
___
### General Labels 
- cosmetic .  indicates if a given feature/bug is mainly cosmetic. (i.e. not huge impact)

**Comment by russellwjoel** [comment]
VERSION 1.0 .  
![screen shot 2019-02-20 at 8 38 46 am](https://user-images.githubusercontent.com/44128527/53109043-f2af1f00-34ec-11e9-8275-2ff60dccb967.png)

**Comment by aanchan** [comment]
You will need to change stale.yml in github wrt to the wontfix label.

**Comment by russellwjoel** [comment]
Abbreviate the prefix for these labels.  i.e.   type-Feature .  --> t:Feature  
shortens tags and allows them to fit on the same line
