### ISSUE TITLE
5. Deployment | Deploy chatbot on ECS

### ISSUE THREAD

**Issue by kirtisynap19** [aanchan/synap-epics#48]
- [ ] Create repositories on ECR for
   - [ ] rasa-core-base 
   - [ ] rasa-nlu
   - [ ] actions
   - [ ] rasa-core (this would only be created after we start services for actions, rasa-nlu, and duckling on ECS)

- [ ] Create secrets in Canada central region for actions task definition (created in next step)

- [ ] Create task definitions on ECS for
   - [ ] rasa-nlu
   - [ ] duckling
   - [ ] actions
   - [ ] rasa-core (this would only be created after we start services for actions, rasa-nlu, and duckling on ECS)

- [ ] Create a Redis cluster (if not already exists)
- [ ] Create a cluster and add these services
   - [ ] rasa-nlu
   - [ ] duckling
   - [ ] actions
   - [ ] rasa-core (this would only be created after we start services for actions, rasa-nlu, and duckling on ECS) 

- [ ] Create codepipeline to deploy actions service: https://stackoverflow.com/questions/55846966/aws-codepipe-webhooks

**Comment by russellwjoel** [comment]
- [x] Create repositories on ECR for
   - [x] rasa-core-base 
   - [x] rasa-nlu
   - [x] actions


- [x] Create secrets in Canada central region for actions task definition (created in next step)

- [x] Create task definitions on ECS for
   - [x] rasa-nlu
   - [x] duckling
   - [x] actions
   - [ ] rasa-core (this would only be created after we start services for actions, rasa-nlu, and duckling on ECS)
- [ ] Create a Redis cluster (if not already exists)
- [ ] Create a cluster and add these services
   - [ ] rasa-nlu
   - [ ] duckling
   - [ ] actions
   - [ ] rasa-core (this would only be created after we start services for actions, rasa-nlu, and duckling on ECS) 

   - [ ] rasa-core (this would only be created after we start services for actions, rasa-nlu, and duckling on ECS)

- [ ] Create codepipeline to deploy actions service: https://stackoverflow.com/questions/55846966/aws-codepipe-webhooks
