### ISSUE TITLE
11. Deployment | Deploy API Gateway using VPC link and cloudformation

### ISSUE THREAD

**Issue by kirtisynap19** [aanchan/synap-epics#56]
Test: Default route should be accessible using public API gateway using curl or browser window showing welcome to Synaptitude.

___
## User
![Screen Shot 2020-02-03 at 10.26.34 AM.png](https://images.zenhubusercontent.com/5c4f4a461b7ec2213049e290/ba2ce2c0-321a-48f9-9a3d-51bf76f5b38d)
___
## Patient
![Screen Shot 2020-02-03 at 10.26.38 AM.png](https://images.zenhubusercontent.com/5c4f4a461b7ec2213049e290/753ac49b-4c1f-4c7e-b0f0-4bac46a3afe4)

![Screen Shot 2020-02-03 at 10.26.42 AM.png](https://images.zenhubusercontent.com/5c4f4a461b7ec2213049e290/4437adbf-8a26-4ca4-aa47-6c1aaeb54ae1)

![Screen Shot 2020-02-03 at 10.26.48 AM.png](https://images.zenhubusercontent.com/5c4f4a461b7ec2213049e290/3452148e-985b-41b1-9ba9-d675bbcd22e6)
___
## Other/Public
![Screen Shot 2020-02-03 at 10.26.53 AM.png](https://images.zenhubusercontent.com/5c4f4a461b7ec2213049e290/bcead924-190c-4dd2-98bd-ba8407337a31)

![Screen Shot 2020-02-03 at 10.26.56 AM.png](https://images.zenhubusercontent.com/5c4f4a461b7ec2213049e290/92847759-2578-428e-b93f-5f783c49cd4f)

![Screen Shot 2020-02-03 at 10.26.59 AM.png](https://images.zenhubusercontent.com/5c4f4a461b7ec2213049e290/0a2a587b-6617-45f6-be05-96beeff19bb3)

**Comment by russellwjoel** [comment]
Note to self: need to determine the API versioning protocol. (these are currently hardcoded in the swagger.yml around the code base.)


![Screen Shot 2020-02-10 at 5.09.51 PM.png](https://images.zenhubusercontent.com/5c4f4a461b7ec2213049e290/0943dab0-2948-42eb-a370-9c0c8cda7766)

**Comment by russellwjoel** [comment]
https://stackoverflow.com/questions/41756190/api-gateway-post-multipart-form-data/41770688#41770688

**Comment by russellwjoel** [comment]
![Screen Shot 2020-03-02 at 4.44.58 PM.png](https://images.zenhubusercontent.com/5c4f4a461b7ec2213049e290/04b4153c-b2ab-4cba-9297-9eff4a3ad422)
https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html#enable-cors-for-resource-using-swagger-importer-tool


https://stackoverflow.com/questions/25594893/how-to-enable-cors-in-flask

https://stackoverflow.com/questions/19962699/flask-restful-cross-domain-issue-with-angular-put-options-methods
